# sqlserver volume claim: sqlserver-volume.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlserver-volume
spec:
  storageClassName: repd-central1-b-c
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi