# sqlserver volume claim: mssql-volume.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlserver-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi